# image will be published to ghcr.io/<user>/<name>
name: bazzite-customized
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      - gcc
      - clang
      - code
      - foot
      - libvirt
      - qemu
      - virt-manager
      - edk2-ovmf
      - intel-one-mono-fonts
      - cascadia-code-fonts
      - jetbrains-mono-fonts
    remove: []

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.obsproject.Studio
        - com.heroicgameslauncher.hgl
        - com.brave.Browser
      remove:
        - org.mozilla.firefox

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
